version: '3.1'

services:

  jupyter:
    image: jupyter/scipy-notebook:400c69639ea5
    container_name: dev_python_jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - 8888:8888
